# 設定ファイル変更時にオートリロード
live_config_reload = true

# [shell]
# program = "/usr/local/bin/fish"

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true 
opacity = 0.9

[font]
normal.family = "Hack Nerd Font"
size = 12
