name: Dotfiles CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # 必要なツールのインストール
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks shellcheck curl
          sudo luarocks install luacheck
      # Styluaのインストール
      - name: Install Stylua
        run: |
          curl -sL https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux-x86_64 -o stylua
          chmod +x stylua
          sudo mv stylua /usr/local/bin/
      # Luaファイルのリント
      - name: Lint Lua files
        run: |
          find . -name "*.lua" -print0 | xargs -0 luacheck || echo "Luacheck found issues, but continuing workflow"
      # Luaファイルのフォーマットチェック
      - name: Check Lua formatting
        run: |
          find . -name "*.lua" -print0 | xargs -0 stylua --check || echo "Stylua found formatting issues, but continuing workflow"
      # シェルスクリプトのリント
      - name: Lint shell scripts
        run: |
          find . -name "*.sh" -print0 | xargs -0 shellcheck || echo "Shellcheck found issues, but continuing workflow"
