name: Dotfiles CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # 必要なツールのインストール
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lua-check shellcheck
      # Styluaのインストール
      - name: Install Stylua
        run: |
          curl -sL https://github.com/JohnnyMorganz/StyLua/releases/latest/download/stylua-linux.zip -o stylua.zip
          unzip stylua.zip -d /usr/local/bin
          chmod +x /usr/local/bin/stylua
      # Luaファイルのリント
      - name: Lint Lua files
        run: |
          find . -name "*.lua" | xargs luacheck
      # Luaファイルのフォーマットチェック
      - name: Check Lua formatting
        run: |
          find . -name "*.lua" | xargs stylua --check
      # シェルスクリプトのリント
      - name: Lint shell scripts
        run: |
          find . -name "*.sh" | xargs shellcheck
